### ISSUE TITLE
Uncertain how to authorize

### ISSUE THREAD

**Issue by tinjaw** [ammaraskar/sphinx-action#1]
I created a PAT and entered it into a secret. However, the action is failing with an authentication error. Do you have more detailed documentation to work on a *private* repo?

**Comment by ammaraskar** [comment]
The `"${{ secrets.GITHUB_TOKEN }}"` should be kept as is. It is a variable that gets [filled in](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#example-passing-github_token-as-an-input) by Github itself.

**Comment by tinjaw** [comment]
Ok. Thanks. This is my first attempt at using actions.

**Comment by ammaraskar** [comment]
Good luck, feel free to close the issue if you get it working or comment if you run into anything else :)

**Comment by tinjaw** [comment]
Made the change, and now it is "working". Now I need to know where to put my files for input and where the files will go from the output.

**Comment by ammaraskar** [comment]
For the input folder, you're gonna have to specify it in the action config with:

`args: "path/to/docs/"`

Currently there's no output but I can look into having the action return the built docs as an artifact.

**Comment by tinjaw** [comment]
Thanks
