### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by MGatner** [ammaraskar/sphinx-action#11]
I'm just getting into Sphinx so please forgive any ignorance... We're working on automating updates to a User Guide compiled with Sphinx (see e.g. https://github.com/codeigniter4/CodeIgniter4/pull/2671#issuecomment-596254480) and I was wondering if there's a hold up for switching the Action definition to use `pip3` in support of Python 3 and the latest Sphinx versions?

**Comment by jreklund** [comment]
I took a closer look at the Dockerfile this project are using: [python:3-slim](https://github.com/docker-library/python/blob/052eee2625b08d678cd58c71abaad0886a32d4ea/3.7/buster/slim/Dockerfile).

And it's using Python 3 with pip. These Ubuntu builds are custom made, it's just the normal Ubuntu Server that have them separated into `pip` and `pip3`.

We can use this project without any issue. So you can close this. @MGatner
