### ISSUE TITLE
Requirements don't install if using -e

### ISSUE THREAD

**Issue by scaramallion** [ammaraskar/sphinx-action#13]
I've been getting an error using a requirements.txt file that contains a `-e` flagged git package. I think (without investigating further) the problem is that `subprocess.check_call()` [here ](https://github.com/ammaraskar/sphinx-action/blob/35082eb35b69713fe335801c4d5846a4cc3c91ff/sphinx_action/action.py#L104)is executing the pip install, which tries to run `git`, however the subprocess doesn't have `PATH` so it fails to find it.

```
Obtaining pydicom from git+git://github.com/pydicom/pydicom.git#egg=pydicom (from -r docs/requirements.txt (line 10))
  Cloning git://github.com/pydicom/pydicom.git to ./src/pydicom
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q git://github.com/pydicom/pydicom.git /github/workspace/src/pydicom
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

requirements.txt
```
numpy
matplotlib
sphinx
pillow
sphinx_rtd_theme
numpydoc
sphinx-gallery
sphinxcontrib-napoleon
sphinx-issues~=1.0
-e git://github.com/pydicom/pydicom.git#egg=pydicom
```

**Comment by ammaraskar** [comment]
The reason this fails is because `git` isn't actually installed on the sphinx building image. It's very light-weight and minimal by default.

You can add `git` in by using:
```yaml
pre-build-command: "apt-get update -y && apt-get install -y git`
```

**Comment by scaramallion** [comment]
Ah thanks! That fixed it
