### ISSUE TITLE
Annotations show on workflow run but not on PR

### ISSUE THREAD

**Issue by lgvaz** [ammaraskar/sphinx-action#15]
Annotations are correctly being raised on the workflow, as you can see [here](https://github.com/lgvaz/mantisshrimp/actions/runs/127338989)

But they are not being added to the related PR file ([link](https://github.com/lgvaz/mantisshrimp/pull/58/files))

Any ideas why this is happening?

**Comment by lgvaz** [comment]
I basically copied the workflow from your example repo

**Comment by ammaraskar** [comment]
Hmm that's weird, seems like a Github bug, could you try closing and re-opening that PR or make a new one just to rule that out?

**Comment by lgvaz** [comment]
Sure! [Here](https://github.com/lgvaz/mantisshrimp/pull/59) is it, same thing

Strange thing that I can even click on "show annotation" and that redirects me to the file without any annotations

![Screenshot 2020-06-07 at 12 39 08 AM](https://user-images.githubusercontent.com/16520544/83959753-4fa42500-a857-11ea-8808-7663cabb623b.png)

**Comment by ammaraskar** [comment]
Oh maybe it's because of the filename being `../README.rst`. Could you try changing a file under `docs/`?

**Comment by lgvaz** [comment]
On spot!!! That was exactly the problem, wow, excellent guess!!

I'm closing this now 😁

Thank you for the help!
