### ISSUE TITLE
sphinx-options are hard-coded

### ISSUE THREAD

**Issue by donsizemore** [ammaraskar/sphinx-action#26]
First off, a wonderful Action!

sphinx_options appear to be hard-coded at
https://github.com/ammaraskar/sphinx-action/blob/master/sphinx_action/action.py#L110

Any chance they could be passed alongside build-command? (or have I missed something)

Thank you,
Don

**Comment by ammaraskar** [comment]
Hey Don. The options are actually passed as part of the build command, so you should just be able to specify the options you want in `build-command` as shown in the [advanced usage](https://github.com/ammaraskar/sphinx-action#advanced-usage). 

For example if you wanted to pass the [`-E` sphinx option](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-E) you would set:

```yaml
  build-command: "sphinx-build -E -b html . _build"
```

**Comment by donsizemore** [comment]
@ammaraskar I've tried several iterations of `build-command`, but as best I can tell the script calls the build command twice, and continues to use the default options. I suspected a typo in the docs (build-command vs. build_command) but that wasn't the case.

```
sphinx-build -b html -d build/doctrees  --keep-going --no-color -w "/tmp/sphinx-log" source build/html
Sphinx v1.5.6
Usage: sphinx-build [options] sourcedir outdir [filenames...]

Filename arguments:
  without -a and without filenames, write new and changed files.
  with -a, write all files.
  with filenames, write these.

sphinx-build: error: no such option: --keep-going
make: *** [Makefile:64: html] Error 2
```

What I'm ultimately after: automatic builds of a required Sphinx version 1.5.6, which isn't new enough to offer --keep-going. Even Sphinx 1.8, which adds this option, breaks search in the end result. I know, get off 1.5.6, but they're not my docs.

**Comment by ammaraskar** [comment]
Oh I see, you're trying to override the `--keep-going --no-color -w` options. Yeah you're right in that there's no way to override that. I think for that use case you're probably better off not using this action because it won't add much value if it can't see the full logs.

The way to do it "manually" is to probably just use the [setup-python](https://github.com/actions/setup-python#usage) action, `pip install` the version of sphinx you want and then invoke it manually.

**Comment by donsizemore** [comment]
An excellent suggestion - thank you!
