### ISSUE TITLE
Creating PDF output?

### ISSUE THREAD

**Issue by mgeier** [ammaraskar/sphinx-action#3]
AFAICT, only `make html` is called, is it possible to create PDF output, too?

I guess you would need a Docker image with LaTeX installed ...
I have used https://github.com/dante-ev/docker-texlive on CircleCI and it worked great, but probably there is a better suited image?

**Comment by ammaraskar** [comment]
Sorry for the late reply, in combination with your other issue this should now be possible. In this test repo I build the pdf and install the tex dependencies before-hand:

https://github.com/ammaraskar/sphinx-action-test/blob/dfbc77eb2ad027cdc3a1e5522b2c73729377724c/.github/workflows/default.yml#L25

**Comment by mgeier** [comment]
Thanks, this is great!
