### ISSUE TITLE
Error with `sphinx==4.1.0`

### ISSUE THREAD

**Issue by ethanwharris** [ammaraskar/sphinx-action#30]
Hi @ammaraskar thanks for this action!

We've noticed that our sphinx build CI has stopped working since the release of sphinx 4.1.0.
Our action is here: https://github.com/PyTorchLightning/pytorch-lightning/blob/e5732a11583572f13c68c02cf50a26fd9863229a/.github/workflows/docs-checks.yml#L11

The error we are getting is:
```
Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/usr/local/lib/python3.8/site-packages/sphinx/deprecation.py))
```

You can see the failing CI here:
https://github.com/PyTorchLightning/pytorch-lightning/pull/7960/checks?check_run_id=3044973574#step:4:435

I'm not sure what the cause of the error is so any help you can give us would be awesome. Thanks :smiley:

**Comment by kapilt** [comment]
That has nothing to do with this action, this action doesn’t import any sphinx code, thats related to your project’s use of sphinx and should be taken to the sphinx community / project to learn more about the error and the upgrade needed in your project’s use of sphinx.

**Comment by ethanwharris** [comment]
Hi @kapilt thanks for the clarification, we weren't really sure about the cause of the error.
