### ISSUE TITLE
[FEATURE REQUEST] html folder to gh-pages branch

### ISSUE THREAD

**Issue by novski** [ammaraskar/sphinx-action#8]
- [ ] It would be nice to add an option to host the static site in an oprhan `gh-pages` branch.
- [ ] Maybe including a single file from: `/docs/_build/latex/REPO-NAME.pdf` if latex was built.

**Comment by ammaraskar** [comment]
Sorry for the late response, this is a great idea! I've made an example of how to do this under my test-repo:

https://github.com/ammaraskar/sphinx-action-test/blob/6921b7a51baab51b0a01c280ed01113f045acbec/.github/workflows/default.yml#L41-L60

The published docs go to http://blog.ammaraskar.com/sphinx-action-test/

Gonna add this to the README.
